# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='uploads/avatars/')),
                ('free_access', models.BooleanField(verbose_name='Zugriff ohne Authentifizierung')),
                ('no_logs', models.BooleanField(verbose_name='Keine Logs')),
                ('pin', models.CharField(max_length=64, verbose_name='Optional Pin')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Guthaben in Euro')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_change', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Guthabenänderung in Euro')),
                ('user_authed', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
