# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 13:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='uploads/avatars/')),
                ('free_access', models.BooleanField(default=False, verbose_name='Zugriff ohne Authentifizierung')),
                ('no_logs', models.BooleanField(default=False, verbose_name='Keine Logs')),
                ('pin', models.CharField(max_length=64, verbose_name='Optional Pin')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Guthaben in Euro')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/products/')),
                ('ean', models.CharField(blank=True, max_length=13)),
                ('price', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_change', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Guthabenänderung in Euro')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('user_authed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.Item')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Menge in l')),
                ('alcoholic', models.IntegerField(null=True)),
                ('caffeine', models.IntegerField(null=True)),
            ],
            bases=('store.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='creating_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='last_update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updater', to=settings.AUTH_USER_MODEL),
        ),
    ]
