# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('ean', models.CharField(max_length=13)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('volume', models.FloatField()),
                ('alcoholic', models.IntegerField(null=True)),
                ('caffeine', models.IntegerField(null=True)),
                ('creating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('last_update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
